name: array_object_adapter
description: >-
  Adapter that is similar to the ObjectAdapter (ArrayObjectAdapter) from the Android Leanback support library.
version: 0.0.2
homepage: https://github.com/michaeldonath
repository: https://github.com/michaeldonath/array-object-adapter
issue_tracker: https://github.com/michaeldonath/array-object-adapter/issues

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter
  # reactive programming: additional capabilities to dart streams and stream-controllers.
  rxdart: ^0.24.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.6.0

flutter:
  uses-material-design: false